os: 
  - windows
  - linux
  - osx
language: c
env:
  - SBCL_VERSION="1.5.7"
install:
  - cd ~
  # Windows - bootstrap from the public 1.4.14 binary
  - SBCL_WINDOWS="http://prdownloads.sourceforge.net/sbcl/sbcl-1.4.14-x86-64-windows-binary.msi"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
    wget $SBCL_WINDOWS -O sbcl.msi; 
    choco install lessmsi make;
    lessmsi x sbcl.msi $(cygpath -w "`pwd`/sbcl_ex/");
    mv "sbcl_ex/SourceDir/PFiles/Steel Bank Common Lisp/1.4.14" sbcl_bin;
    export SBCL_HOME="`pwd`/sbcl_bin";
    export PATH="`pwd`/sbcl_bin:${PATH}";
    fi
  # macOS - use homebrew
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
    HOMEBREW_NO_AUTO_UPDATE=1 brew install sbcl;
    fi
  # Linux - use apt
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    sudo apt update; sudo apt install sbcl; 
    fi
  # Build new SBCL from source
  - SBCL_SOURCE="http://downloads.sourceforge.net/project/sbcl/sbcl/$SBCL_VERSION/sbcl-$SBCL_VERSION-source.tar.bz2"
  - wget $SBCL_SOURCE -O sbcl.tar.bz2
  - tar -xf sbcl.tar.bz2
  - cd "sbcl-$SBCL_VERSION"
  - sh make.sh
  - unset SBCL_HOME
  - INSTALL_ROOT=~/sbcl ./install.sh
  - export SBCL_HOME="$HOME/sbcl/lib/sbcl"
  - export PATH="$HOME/sbcl/bin:${PATH}"
    # Install Quicklisp
  - wget https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --disable-debugger
    --eval "(load \"quicklisp.lisp\")" 
    --eval "(quicklisp-quickstart:install)"
    --eval "(ql-util:without-prompting (ql:add-to-init-file))"
    --eval "(ql:update-all-dists)"
    --eval "(sb-ext:exit)"
script:
  - mv build/phoe-trash/furcadia-post-splitter ~/quicklisp/local-projects
  - sbcl --disable-debugger
    --eval "(ql:quickload :furcadia-post-splitter)"
