os: 
  - windows
  #- linux
  #- osx
language: c
install:
  # Windows
  - SBCL_WINDOWS="http://prdownloads.sourceforge.net/sbcl/sbcl-1.4.14-x86-64-windows-binary.msi"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget $SBCL_WINDOWS -O sbcl.msi; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install lessmsi; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then lessmsi x sbcl.msi $(cygpath -w "`pwd`/sbcl_ex/"); fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mv "sbcl_ex/SourceDir/PFiles/Steel Bank Common Lisp/1.4.14" sbcl; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export SBCL_HOME="`pwd`/sbcl_bin"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="`pwd`/sbcl_bin:${PATH}"; fi
  # TODO: build new SBCL
  # macOS
  - if [ "$TRAVIS_OS_NAME" = "osx" ]    ; then HOMEBREW_NO_AUTO_UPDATE=1 brew install sbcl; fi
  # Linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]  ; then sudo apt update; sudo apt install sbcl; fi
  # TODO: build new SBCL
script:
  # Install
  - sbcl --eval "(print (list :hello-world (lisp-implementation-type) (lisp-implementation-version)))"
    --eval "(finish-output)" --eval "(sb-ext:exit)"
